<?php

/**
 * @file
 * Scans chemical inventory item content types and looks for changes to the MSDS file and updates node expiry date as needed.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param string path
 *   Which path of the site we're using to display help.
 * @param array arg
 *   Holds the current path as returned from arg() function.
 * @return string
 *  Help description.
 */
function roblib_field_expire_help($path, $arg) {
  switch ($path) {
    case "admin/help#roblib_field_expire":
      return '<p>' . t("Scans chemical inventory item content types and looks for changes to the MSDS file and " .
                           "updates node expiry date as needed.") . '</p>';
      break;
  }
}

/**
 * Implements hook_node_presave().
 *
 * Scans chemical inventory item content types and looks for changes to the MSDS file and updates node expiry date as needed.
 *
 * @param node
 *   Drupal's node array.
 */
function roblib_field_expire_node_presave($node) {

  // Only concerned with existing chemical inventory item content types
  if((! $node->is_new) AND $node->type == 'chemical_inventory_item') {

    $original_msds_file = $node->original->field_msds_url;
    $new_msds_file = $node->field_msds_url;

    // Reset node expire date only when MSDS file or URL fields are changed
    if($original_msds_file[LANGUAGE_NONE][0]['fid'] != $new_msds_file[LANGUAGE_NONE][0]['fid']) {

      $today_date = date('Y-m-d', time());
      $temp = variable_get('node_expire_ntypes', '');

      // Set default expire adjustment to +3 years if not already set by node_expire module
      $default_expire_adjustment = $temp['inventory_item']['default'] ? $temp['inventory_item']['default'] : '+3 years';

      // Set expire date to today's date + expire adjustment
      $node->expire = date('Y-m-d', strtotime($today_date . $default_expire_adjustment));

      // Reset expired flag in case the node had been expired
      $node->expired = 0;

      drupal_set_message('MSDS file change detected.' . ' Resetting expire date to ' . $default_expire_adjustment .
        ' from today.', 'status');
    }
    else {
      drupal_set_message('Non MSDS edits detected. Expire date will NOT reset.', 'status');
    }
  }
}
